#!/bin/sh
set -e

case "$1" in
    configure)
        # Use the official systemd helper if it exists
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
            echo "Enabling CoreStationHXAgent Service..."
            deb-systemd-helper enable CoreStationHXAgent.service >/dev/null || true
            echo "Starting CoreStationHXAgent Service..."
            deb-systemd-helper start CoreStationHXAgent.service >/dev/null || true
        else
            # Fallback for older systems
            echo "Enabling CoreStationHXAgent Service..."
            systemctl enable CoreStationHXAgent.service >/dev/null || true
            echo "Starting CoreStationHXAgent Service..."
            systemctl restart CoreStationHXAgent.service >/dev/null || true
        fi
    ;;
esac

exit 0