#!/bin/sh
set -e

case "$1" in
    remove|upgrade)
        # Use the official systemd helper if it exists
        echo "Stopping CoreStationHXAgent Service..."
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
            deb-systemd-helper stop CoreStationHXAgent.service >/dev/null || true
        fi
    ;;
esac

#DEBHELPER#

exit 0