#!/bin/sh
set -e

case "$1" in
    purge|remove|upgrade)
        # Use the official systemd helper if it exists
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
            deb-systemd-helper disable CoreStationHXAgent.service >/dev/null || true
            deb-systemd-helper purge CoreStationHXAgent.service >/dev/null || true
        else
            echo "Disbling CoreStationHXAgent Service..."
            systemctl disable CoreStationHXAgent.service
        fi
    ;;
esac

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'CoreStationHXAgent.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0