#!/bin/sh
set -e

case "$1" in
    remove|upgrade)
        # Use the official systemd helper if it exists
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
            echo "Stopping CoreStationHXAgent Service..."
            deb-systemd-helper stop CoreStationHXAgent.service >/dev/null || true
        else
            # Fallback for older systems
            echo "Stopping CoreStationHXAgent Service..."
            systemctl stop CoreStationHXAgent.service >/dev/null || true
        fi
    ;;
esac

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'CoreStationHXAgent.service' >/dev/null || true
fi
# End automatically added section


exit 0