; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "CoreStation HX Agent"
#define MyAppVersion "20.25.12.1_rc1"
#define MyAppPublisher "Amulet Hotkey LTD"
#define MyAppURL "https://www.amulethotkey.com/"
#define MyAppExeName "CoreStationHXAgent.exe"
#define MyServiceName "CoreStationService"
#define MyServiceInstallScript "install.ps1"
#define MyServiceUninstallScript "remove.ps1"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=CoreStation_Management_Service
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL= https://www.amulethotkey.com/support/
DefaultDirName={autopf}\CoreStation HX Agent
DisableDirPage=yes
DefaultGroupName=Amulet Hotkey
DisableProgramGroupPage=yes
CreateAppDir=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
PrivilegesRequired=admin
OutputBaseFilename=CoreStation HX Agent Installer {#MyAppVersion}
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=win64
SetupIconFile=logo.ico
AlwaysRestart=yes
MinVersion=10.0.19045

VersionInfoCompany=Amulet Hotkey
VersionInfoCopyright=© Amulet Hotkey 2025
AppCopyright=© Amulet Hotkey 2025
VersionInfoDescription=CoreStation HX Agent installer
VersionInfoProductTextVersion=20.25.12.1
VersionInfoProductVersion=20.25.12.1
VersionInfoVersion=20.25.12.1
VersionInfoProductName=CoreStation HX Agent Installer

SetupLogging=yes

WizardImageFile=compiler:WizClassicImage.bmp
WizardSmallImageFile=compiler:WizClassicSmallImage.bmp
ShowLanguageDialog=no
UninstallDisplayIcon={app}\logo.ico
UninstallDisplayName={#MyAppName}

Compression=lzma2/ultra64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: ".\install.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\CoreStationHXAgent.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\remove.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\logo.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Uninstall CoreStation HX Agent"; Filename: "{uninstallexe}"; IconFilename: "{app}\logo.ico"; 


[Run]
; Stop existing service if running
Filename: "powershell.exe"; \
  Parameters: "-ExecutionPolicy Bypass -NoProfile -Command ""Stop-Service -Name '{#MyServiceName}' -Force -ErrorAction SilentlyContinue"""; \
  Flags: runhidden waituntilterminated; \
  StatusMsg: "Stopping existing service..."; \
  Check: CheckPowerShellAvailable

; Install and start service
Filename: "powershell.exe"; \
  Parameters: "-ExecutionPolicy Bypass -NoProfile -File ""{app}\{#MyServiceInstallScript}"""; \
  WorkingDir: "{app}"; \
  Flags: runhidden waituntilterminated; \
  StatusMsg: "Installing {#MyAppName}..."; \
  Check: CheckPowerShellAvailable
  
[Code]
// Check if PowerShell is available
function CheckPowerShellAvailable: Boolean;
var
  ResultCode: Integer;
begin
  Result := Exec('powershell.exe', '-Command "exit 0"', '', SW_HIDE, 
                 ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
  
  if not Result then
  begin
    MsgBox('PowerShell is required but not available. Installation cannot continue.', 
           mbError, MB_OK);
  end;
end;

// Initialize setup - check prerequisites
function InitializeSetup(): Boolean;
var
  Version: TWindowsVersion;
begin
  Result := True;
  GetWindowsVersionEx(Version);
  
  // Verify Windows version
  if (Version.Major < 10) or 
     ((Version.Major = 10) and (Version.Build < 19045)) then
  begin
    MsgBox('This application requires Windows 10 build 19045 (21H2) or later.' + #13#10 +
           'Current version: ' + IntToStr(Version.Major) + '.' + IntToStr(Version.Minor) + 
           ' (Build ' + IntToStr(Version.Build) + ')', 
           mbError, MB_OK);
    Result := False;
  end;
end;

// Handle uninstall
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
begin
  if CurUninstallStep = usUninstall then
  begin
    // Ensure service is stopped before file removal
    Exec('powershell.exe', 
         '-ExecutionPolicy Bypass -NoProfile -Command "Stop-Service -Name ''' + 
         '{#MyServiceName}' + ''' -Force -ErrorAction SilentlyContinue"',
         '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Sleep(2000); // Give service time to fully stop
  end;
end;
 
[UninstallRun]
Filename: "powershell.exe"; \
  Parameters: "-ExecutionPolicy Bypass -NoProfile -File ""{app}\{#MyServiceUninstallScript}"""; \
  WorkingDir: "{app}"; \
  Flags: runhidden waituntilterminated; \
  StatusMsg: "Uninstalling CoreStation HX Agent..."
  
[UninstallDelete]
Type: filesandordirs; Name: "{app}"
